version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"  
    depends_on:
      - redis
      - mongo  
    environment:
      LONG_TOKEN_SECRET: "${{ secrets.LONG_TOKEN_SECRET }}"
      SHORT_TOKEN_SECRET: "${{ secrets.SHORT_TOKEN_SECRET }}"
      NACL_SECRET: "${{ secrets.SHORT_TOKEN_SECRET }}"
      MONGO_URI: "${{ secrets.MONGO_URI }}"

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:  
    image: mongo
    ports:
      - "27017:27017"  